[language-server.nil]
command = "nil"

[[language]]
name = "nix"
file-types = ["nix"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
formatter = { command = "nixfmt-rfc-style" }
language-servers = [ "nil" ]
