name: "cache test"
on: [workflow_dispatch]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  NIX_STORE_SIGN_PRIVATE: ${{ secrets.NIX_STORE_SIGN_PRIVATE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 13
    - uses: docker/setup-qemu-action@master
    - uses: nixbuild/nix-quick-install-action@master
      with:
        nix_conf: |
          extra-platforms = aarch64-linux
          experimental-features = nix-command flakes
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.mlyxshi.com:qbWevQEhY/rV6wa21Jaivh+Lw2AArTFwCB2J6ll4xOI=
          substituters = https://cache.nixos.org https://cache.mlyxshi.com
    
    - run: echo $NIX_STORE_SIGN_PRIVATE > /tmp/key
    # Oracle x86_64 
    - run: nix copy --to 's3://nix?scheme=http&endpoint=proxy.mlyxshi.com&secret-key=/tmp/key&parallel-compression=true&compression=zstd&compression-level=20' .#nixosConfigurations.hk1.config.system.build.toplevel 
    # - run: nix copy --to 's3://nix?endpoint=minio.mlyxshi.com&secret-key=/tmp/key&parallel-compression=true&compression=zstd&compression-level=20' .#nixosConfigurations.sw2.config.system.build.toplevel 
    # - run: nix copy --to 's3://nix?endpoint=minio.mlyxshi.com&secret-key=/tmp/key&parallel-compression=true&compression=zstd&compression-level=20' .#nixosConfigurations.sw3.config.system.build.toplevel
    # # Azure x86_64
    # - run: nix copy --to 's3://nix?endpoint=minio.mlyxshi.com&secret-key=/tmp/key&parallel-compression=true&compression=zstd&compression-level=20' .#nixosConfigurations.hk1.config.system.build.toplevel 
    # - run: nix copy --to 's3://nix?endpoint=minio.mlyxshi.com&secret-key=/tmp/key&parallel-compression=true&compression=zstd&compression-level=20' .#nixosConfigurations.hk2.config.system.build.toplevel
    # - run: nix copy --to 's3://nix?endpoint=minio.mlyxshi.com&secret-key=/tmp/key&parallel-compression=true&compression=zstd&compression-level=20' .#nixosConfigurations.jp3.config.system.build.toplevel
    # # Oracle aarch64
    # - run: nix copy --to 's3://nix?endpoint=minio.mlyxshi.com&secret-key=/tmp/key&parallel-compression=true&compression=zstd&compression-level=20' .#nixosConfigurations.jp2.config.system.build.toplevel 
    # - run: nix copy --to 's3://nix?endpoint=minio.mlyxshi.com&secret-key=/tmp/key&parallel-compression=true&compression=zstd&compression-level=20' .#nixosConfigurations.jp4.config.system.build.toplevel
    # - run: nix copy --to 's3://nix?endpoint=minio.mlyxshi.com&secret-key=/tmp/key&parallel-compression=true&compression=zstd&compression-level=20' .#nixosConfigurations.sw.config.system.build.toplevel
    # - run: nix copy --to 's3://nix?endpoint=minio.mlyxshi.com&secret-key=/tmp/key&parallel-compression=true&compression=zstd&compression-level=20' .#nixosConfigurations.us1.config.system.build.toplevel
    # - run: nix copy --to 's3://nix?endpoint=minio.mlyxshi.com&secret-key=/tmp/key&parallel-compression=true&compression=zstd&compression-level=20' .#nixosConfigurations.au.config.system.build.toplevel