name: "Update x86_64"
on: [workflow_dispatch]
jobs:
  sw2:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ github.job }}.mlyxshi.com update 
  sw3:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ github.job }}.mlyxshi.com update 
  kr2:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ github.job }}.mlyxshi.com update 
  hk1:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ github.job }}.mlyxshi.com update 
  hk2:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ github.job }}.mlyxshi.com update 
  jp3:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ github.job }}.mlyxshi.com update 