name: "System Upgrade"
on:
  push:
    paths: 
      - 'flake.lock'
  workflow_dispatch:

jobs:
  x86-64:
    runs-on: ubuntu-latest  
    strategy:
      fail-fast: false
      matrix:
        host: [sw2, sw3] # kr2: hydra x86-64 
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ matrix.host }}.mlyxshi.com '[ -e "/persist/flake" ] && rm -rf /persist/flake; systemctl stop KeepCPUMemory; update'

  aarch64:
    runs-on: ubuntu-latest   
    strategy:
      fail-fast: false
      matrix:
        host: [jp2,jp4,sw,de,us1,us2,au] # kr: hydra aarch64 
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ matrix.host }}.mlyxshi.com '[ -e "/persist/flake" ] && rm -rf /persist/flake; systemctl stop KeepCPUMemory; update'