# Generated by ./update.sh - do not update manually!
# Last updated: 2026-01-12
{
  version = "5.0.1";
  x86_64-linux = {
    url = "https://dl.nssurge.com/snell/snell-server-v5.0.1-linux-amd64.zip";
    hash = "sha256-m+ocK541tzsxY0hWwE0Yw5MHK55dzeajJ4HYuPkIxTk=";
  };
  aarch64-linux = {
    url = "https://dl.nssurge.com/snell/snell-server-v5.0.1-linux-aarch64.zip";
    hash = "sha256-LxeL9axGjOGhMEVO+kCgYD+75OR+zEiAqYn0q8f4JM8=";
  };
}
