version=$(curl -s https://kb.nssurge.com/surge-knowledge-base/release-notes/snell \
  | grep -oE 'snell-server-v[0-9]+\.[0-9]+\.[0-9]+' \
  | sed 's/snell-server-v//' \
  | sort -V | tail -n1)
  
linux_amd64_url="https://dl.nssurge.com/snell/snell-server-v${version}-linux-amd64.zip"
linux_arm64_url="https://dl.nssurge.com/snell/snell-server-v${version}-linux-aarch64.zip"

linux_amd64_hash=$(nix hash convert --to sri --hash-algo sha256 $(nix-prefetch-url $linux_amd64_url))
linux_arm64_hash=$(nix hash convert --to sri --hash-algo sha256 $(nix-prefetch-url $linux_arm64_url))

cd "$(dirname "${BASH_SOURCE[0]}")"

cat > sources.nix <<EOF
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%F)
{
  version = "$version";
  x86_64-linux = {
    url = "$linux_amd64_url";
    hash = "$linux_amd64_hash";
  };
  aarch64-linux = {
    url = "$linux_arm64_url";
    hash = "$linux_arm64_hash";
  };
}
EOF