version=$(curl -s https://kb.nssurge.com/surge-knowledge-base/release-notes/snell  | grep -o 'snell-server-v[0-9][0-9.]*-linux-amd64\.zip' \
  | sed 's/snell-server-v//; s/-linux-amd64\.zip//' \
  | sort -V | tail -n1)
  
x86_64_url="https://dl.nssurge.com/snell/snell-server-v${version}-linux-amd64.zip"
aarch64_url= "https://dl.nssurge.com/snell/snell-server-v${version}-linux-aarch64.zip"

x86_64_hash=$(nix hash convert --to sri --hash-algo sha256 $(nix-prefetch-url $x86_64_url))
aarch64_hash=$(nix hash convert --to sri --hash-algo sha256 $(nix-prefetch-url $aarch64_url))

cat >sources.nix <<EOF
# Generated by ./update.sh - do not update manually!
# Last updated: $(date +%F)
{
  version = "$version";
  x86_64-linux = {
    url = "$x86_64_url";
    hash = "$x86_64_hash";
  };
  aarch64-linux = {
    url = "$x86_64_url";
    hash = "$aarch64_hash";
  };
}
EOF