name: "[Auto] update firefox version"
on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  AutoUpdateFirefox:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.shell.outputs.latestVersion }}
    steps:
    - uses: actions/checkout@v3
    - uses: nixbuild/nix-quick-install-action@v19
    - name: Shell Script
      id: shell
      run: |

        latestVersion=$(curl --silent https://product-details.mozilla.org/1.0/firefox_versions.json | jq '.LATEST_FIREFOX_VERSION' | tr -d '"')
        currentVersion=$(curl --silent "https://raw.githubusercontent.com/mlyxshi/flake/main/config/firefox/version.json"| jq ".version" | tr -d '"')       
        
        currentDarwinHash=$(curl --silent "https://raw.githubusercontent.com/mlyxshi/flake/main/config/firefox/version.json"| jq ".darwin.sha256" | tr -d '"') 
        latestDarwinUrl="https://download-installer.cdn.mozilla.net/pub/firefox/releases/${latestVersion}/mac/en-US/Firefox%20${latestVersion}.dmg"
        latestDarwinHash=$(nix-prefetch-url  --name "firefox-${latestVersion}.dmg" "${latestDarwinUrl}")

        [[ $currentVersion == $latestVersion ]] && echo "latestVersion=0" >> $GITHUB_OUTPUT || echo "latestVersion=$latestVersion" >> $GITHUB_OUTPUT
        
        cat > ${GITHUB_WORKSPACE}/config/firefox/version.json <<EOF
        {
          "version": "$latestVersion",
          "darwin": {
            "url": "$latestDarwinUrl",
            "sha256": "$latestDarwinHash"
          },
          "description": "[Auto-Generated] Firefox Stable Version"
        }
        EOF

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        branch: update-firefox
        title: '[Auto] Update Firefox'
        body: |
          Update report
          - Updated with Firefox Version
          - Auto-generated
        assignees: mlyxshi
        reviewers: mlyxshi




  SendTG:
    runs-on: ubuntu-latest
    needs: AutoUpdateFirefox
    if: needs.AutoUpdateFirefox.outputs.version !=0
    steps:
    - name: send firefox info
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TG_CHAT_ID }}
        token: ${{ secrets.TG_TOKEN }}
        message: |
          Firefox Update: ${{needs.AutoUpdateFirefox.outputs.version}}

          https://www.mozilla.org/en-US/firefox/${{needs.AutoUpdateFirefox.outputs.version}}/releasenotes/
