name: "Update aarch64"
on: [workflow_dispatch]
jobs:
  jp2:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ github.job }}.mlyxshi.com update 
  jp4:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ github.job }}.mlyxshi.com update 
  sw:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ github.job }}.mlyxshi.com update 
  de:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ github.job }}.mlyxshi.com update 
  us1:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ github.job }}.mlyxshi.com update 
  us2:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ github.job }}.mlyxshi.com update 
  au:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ github.job }}.mlyxshi.com update 
  kr:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ github.job }}.mlyxshi.com update 