#!/bin/sh

# mount important directories
mkdir -p /dev /proc /sys /run
mount -t devtmpfs devtmpfs /dev
mount -t proc procfs /proc
mount -t sysfs sysfs /sys
mount -t tmpfs tmpfs /run

ln -sfn /proc/self/fd /dev/fd
ln -sfn /proc/self/fd/0 /dev/stdin
ln -sfn /proc/self/fd/1 /dev/stdout
ln -sfn /proc/self/fd/2 /dev/stderr


mkdir /etc
touch /etc/initrd-release

modprobe virtio_scsi 
modprobe af_packet

# default eth0,default.script
udhcpc -q

/bin/sh