#!/bin/busybox sh

for i in sh ln cd ls cat free poweroff reboot dd mkdir mount ps ip ifconfig udhcpc wget tcpsvd; do
  /bin/busybox ln -s /bin/busybox /bin/$i
done

mkdir -p /dev /proc /sys /run
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /run

ln -s /proc/self/fd /dev/fd
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr

mkdir /etc
echo "" > /etc/initrd-release

# only support nocloud network-config version1
setup_cloud_init_net() {
  mkdir /cloud-init
  mount $(blkid -L cidata) /cloud-init
  eval $(cloud-init-networkcfg /cloud-init/network-config)
  ifconfig eth0 "$IP" netmask "$NETMASK" up
  [ "$NETMASK" = "255.255.255.255" ] && ONLINK="onlink"
  ip route add default via "$GATEWAY" dev eth0 $ONLINK
  echo "nameserver 1.1.1.1" > /etc/resolv.conf
}

ip link set eth0 up
# -q: exit immediately after lease;  -n: Exit if no lease obtained after 9s
udhcpc -i eth0 -s /bin/udhcpc-script.sh -q -n || setup_cloud_init_net

# sshd
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts
mkdir -p /root/.ssh/ /etc/tinyssh/
echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMpaY3LyCW4HHqbp4SA4tnA+1Bkgwrtro2s/DEsBcPDe" > /root/.ssh/authorized_keys
ln -s /bin/tinysshd /bin/tinysshd-makekey
tinysshd-makekey /etc/tinyssh/sshkeydir
echo "root:x:0:0:root:/root:/bin/sh" > /etc/passwd
tcpsvd -v 0 22 tinysshd -v /etc/tinyssh/sshkeydir > /run/sshd.log 2>&1 &

/bin/sh