#!/bin/toybox sh

for i in sh ln cd ls echo cat free poweroff reboot dd mkdir mount blkid ps ip dhcp wget netcat; do
  /bin/toybox ln -s /bin/toybox /bin/$i
done

mkdir -p /dev /proc /sys
mount -t devtmpfs none /dev
mount -t proc none /proc
mount -t sysfs none /sys

ln -s /proc/self/fd /dev/fd
ln -s /proc/self/fd/0 /dev/stdin
ln -s /proc/self/fd/1 /dev/stdout
ln -s /proc/self/fd/2 /dev/stderr

mkdir /etc
ip link set eth0 up

# Check for the cloud-init nocloud volume
CIDATA_DEV=$(blkid -L cidata)

if [ -n "$CIDATA_DEV" ]; then
  echo "Configuring via cidata..."
  mkdir /cloud-init
  mount "$CIDATA_DEV" /cloud-init
  eval $(cloud-init-networkcfg /cloud-init/network-config)
  ip addr add "$IP/$PREFIX" dev eth0
  ip route add $GATEWAY dev eth0 
  ip route add default via $GATEWAY
  echo "nameserver 1.1.1.1" > /etc/resolv.conf
else
  # -q: exit immediately after lease;  -n: Exit if no lease obtained after 9s
  dhcp -i eth0 -s /bin/udhcpc-script.sh -q -n
fi

ip link set lo up
netcat -l -p 23333 /bin/sh &

/bin/sh