#!/bin/busybox sh

/bin/busybox --install -s /bin

mkdir -p /dev /proc /sys /etc
mount -t devtmpfs none /dev
mount -t proc    none /proc
mount -t sysfs   none /sys

# only support nocloud network-config version1
setup_cloud_init_net() {
  mkdir /cloud-init
  mount $(cloud-init-networkcfg -L cidata) /cloud-init
  eval $(cloud-init-networkcfg /cloud-init/network-config)
  ip addr add "$IP/$PREFIX" dev eth0
  ip route add default via $GATEWAY dev eth0 $ONLINK
  echo "nameserver 1.1.1.1" > /etc/resolv.conf
  ip addr show eth0
  ip route show
}


ip link set eth0 up
# -q: exit immediately after lease;  -n: exit if no lease obtained after 9s
udhcpc -i eth0 -s /bin/udhcpc-script.sh -q -n || setup_cloud_init_net

DEVICE= URL=
for arg in $(cat /proc/cmdline); do
  case $arg in
    device=*) DEVICE=${arg#device=} ;;
    url=*)    URL=${arg#url=} ;;
  esac
done

if [ -n "$DEVICE" ]; then
  echo "Target Device: $DEVICE | Target URL: $URL"
  wget -qO "$DEVICE" "$URL"
  reboot -f
else
  nc -l -p 23333 -e /bin/sh &
fi

exec /bin/sh