runs:
  using: composite
  steps:
    - name: System Build
      shell: bash
      run: |
        outPath=$(nix build --no-link --print-out-paths .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel)
        echo "outPath=$outPath" >> "$GITHUB_ENV"

    - name: Nix copy
      shell: bash
      run:  nix copy --substitute-on-destination --to ssh://${{ matrix.host }} $outPath
    
    - name: Diff closures
      shell: bash
      run:  ssh ${{ matrix.host }} nix store diff-closures /run/current-system $outPath
    
    - name: Set system profile
      shell: bash
      run:  ssh ${{ matrix.host }} nix-env -p /nix/var/nix/profiles/system --set $outPath
    
    - name: Switch configuration
      shell: bash
      run:  ssh ${{ matrix.host }} $outPath/bin/switch-to-configuration switch




