name: "Package Cache"
on:
  push:
    paths: 
      - 'pkgs/transmission/default.nix'
      - 'flake.lock'
  workflow_dispatch:

env:
  ORANC_SIGNING_KEY: ${{ secrets.NIX_STORE_SIGN_PRIVATE }}
  ORANC_USERNAME: mlyxshi
  ORANC_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    services:
      oranc:
        image: ghcr.io/linyinfeng/oranc
    steps:
    - uses: actions/checkout@master
    - uses: docker/setup-qemu-action@master
    - uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 13
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          extra-platforms = aarch64-linux

    - run: nix profile install github:linyinfeng/oranc  --extra-substituters https://linyinfeng.cachix.org --extra-trusted-public-keys linyinfeng.cachix.org-1:sPYQXcNrnCf7Vr7T0YmjXz5dMZ7aOKG3EqLja0xr9MM=
    
    - run: oranc push --registry ghcr.io --repository oranc-cache initialize