name: "Create DD image"
on:
  workflow_dispatch:

jobs:
  bios-init:
    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main
    - run: |
        mkdir -m 0755  ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
  
        mkdir ~/.oci
        echo "${{ secrets.OCI_CONFIG }}" > ~/.oci/config
        echo "${{ secrets.OCI_API_KEY}}" > ~/.oci/oci_api_key.pem  
        chmod 600 ~/.oci/config
        chmod 600 ~/.oci/oci_api_key.pem

        mkdir -p ~/.config/rclone
        echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

    - name: System Build
      run: |
        fallocate -l 3G bios-init.raw
        sudo losetup -fP --show bios-init.raw

        sudo sgdisk -n 0:0:+1M -t 0:ef02 /dev/loop0

        sudo sgdisk -n 0:0:+200M /dev/loop0
        sudo sgdisk -n 0:0:0 /dev/loop0

        sudo mkfs.fat -F 32 /dev/loop0p2
        sudo mkfs.ext4 /dev/loop0p3
        sudo mkdir -p /mnt
        sudo mount /dev/loop0p3 /mnt
        sudo mount --mkdir /dev/loop0p2 /mnt/boot

        outPath=$(sudo /nix/var/nix/profiles/default/bin/nix build --store /mnt --no-link --print-out-paths .#nixosConfigurations.bios-vda-init.config.system.build.toplevel)
        sudo /nix/var/nix/profiles/default/bin/nix-env --store /mnt -p /mnt/nix/var/nix/profiles/system --set $outPath

        sudo mkdir -p /mnt/dev /mnt/sys /mnt/proc
        sudo chmod 0755 /mnt/dev /mnt/sys /mnt/proc
        sudo mount --rbind /dev /mnt/dev
        sudo mount --rbind /sys /mnt/sys
        sudo mount --rbind /proc /mnt/proc

        sudo mkdir /mnt/etc
        sudo chroot /mnt /nix/var/nix/profiles/system/activate
        sudo chroot /mnt /nix/var/nix/profiles/system/bin/switch-to-configuration boot

        sudo /nix/var/nix/profiles/default/bin/nix run nixpkgs#limine bios-install /dev/loop0

        sudo umount -Rl /mnt/dev
        sudo umount -Rl /mnt/sys
        sudo umount -Rl /mnt/proc
        sudo umount -Rl /mnt/run
        sudo umount -Rl /mnt/etc


        sudo umount /dev/loop0p2
        sudo umount /dev/loop0p3
        sudo losetup -d /dev/loop0


    - name: Upload
      run: nix run nixpkgs#rclone copy  bios-init.raw  oracle:us



  amd-init:
    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main
    - run: |
        mkdir -m 0755  ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
  
        mkdir ~/.oci
        echo "${{ secrets.OCI_CONFIG }}" > ~/.oci/config
        echo "${{ secrets.OCI_API_KEY}}" > ~/.oci/oci_api_key.pem  
        chmod 600 ~/.oci/config
        chmod 600 ~/.oci/oci_api_key.pem

        mkdir -p ~/.config/rclone
        echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

    - name: System Build
      run: |
        outPath=$(sudo /nix/var/nix/profiles/default/bin/nix --no-link --print-out-paths .#nixosConfigurations.amd-init.config.system.build.image)
        echo "outPath=$outPath" >> "$GITHUB_ENV"

    - name: Upload
      run: nix run nixpkgs#rclone copy $outPath/amd-init.raw  oracle:us


  arm-init:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main
    - run: |
        mkdir -m 0755  ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
  
        mkdir ~/.oci
        echo "${{ secrets.OCI_CONFIG }}" > ~/.oci/config
        echo "${{ secrets.OCI_API_KEY}}" > ~/.oci/oci_api_key.pem  
        chmod 600 ~/.oci/config
        chmod 600 ~/.oci/oci_api_key.pem

        mkdir -p ~/.config/rclone
        echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

    - name: System Build
      run: |
        outPath=$(sudo /nix/var/nix/profiles/default/bin/nix --no-link --print-out-paths .#nixosConfigurations.arm-init.config.system.build.image)
        echo "outPath=$outPath" >> "$GITHUB_ENV"

    - name: Upload
      run: nix run nixpkgs#rclone copy $outPath/arm-init.raw  oracle:us