name: "Install OS"
on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'ip or domain'
        type: string
        required: true
      host:
        description: 'os config hostname'
        type: string
        required: true
      user:
        description: 'ssh user'
        required: true
        default: 'root'
        type: choice
        options:
          - ubuntu
          - root

jobs:

  kexec:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    
    - run: |
        mkdir -m 0755  ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
    - run: |
        ssh -o ConnectTimeout=5 StrictHostKeyChecking=no ${{ inputs.user }}@${{ inputs.ip }} \
        'sudo curl -sL http://hydra.mlyxshi.com/job/nixos/flake/kexec-$(uname -m)/latest/download-by-type/file/kexec-script | bash -s'

  dd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main
    
    - run: |
        mkdir -m 0755  ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - run: |
        image=$(nix build --no-link --print-out-paths .#nixosConfigurations.${{ inputs.host }}.config.system.build.image)
        echo "imagePath=$image" >> "$GITHUB_ENV"
    
    - run: |
        dd if=$imagePath/image.raw bs=5M conv=fsync status=progress | gzip -1 -c | \
        ssh -o StrictHostKeyChecking=no root@${{ inputs.ip }} \
        "gzip -d | dd of=/dev/sda bs=5M && mount /dev/sda2 /tmp && mkdir -p /tmp/persist/sops/ && curl -sLo /tmp/persist/sops/key ${{ secrets.AGE_KEY_URL }} &&reboot"