name: "Install OS"
on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'ip or domain'
        type: string
        required: true
      host:
        description: 'os config hostname'
        type: string
        required: true
      user:
        description: 'ssh user'
        required: true
        default: 'root'
        type: choice
        options:
          - root
          - ubuntu
      arch:
        required: true
        default: 'aarch64'
        type: choice
        options:
          - aarch64
          - x86_64

jobs:

  kexec:
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 2
    steps:
    
    - run: |
        mkdir -m 0755  ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
    - run: |
        ssh -o StrictHostKeyChecking=no ${{ inputs.user }}@${{ inputs.ip }} \
        'curl -sL http://hydra.mlyxshi.com/job/nixos/flake/kexec-$(uname -m)/latest/download-by-type/file/kexec-script | sudo bash -s'

  dd-x86_64:
    if: inputs.arch == 'x86_64'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main
    
    - run: |
        mkdir -m 0755  ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - run: |
        image=$(nix build --no-link --print-out-paths .#nixosConfigurations.${{ inputs.host }}.config.system.build.image)
        echo "imagePath=$image" >> "$GITHUB_ENV"
    
    - run: |
        dd if=$imagePath/image.raw bs=5M conv=fsync status=progress | gzip -1 -c | \
          ssh -o StrictHostKeyChecking=no root@${{ inputs.ip }} \
          "gzip -d | dd of=/dev/sda bs=5M && mount /dev/sda2 /tmp && mkdir -p /tmp/persist/sops/ && curl -sLo /tmp/persist/sops/key ${{ secrets.AGE_KEY_URL }} && reboot"

  dd-aarch64:
    if: inputs.arch == 'aarch64'
    runs-on: ubuntu-latest
    steps:

    - run: |
        mkdir -m 0755  ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - run: |
        ssh -o StrictHostKeyChecking=no root@kr.mlyxshi.com  "os-dd ${{ inputs.host }} ${{ inputs.ip }} ${{ secrets.AGE_KEY_URL }}"

  Notify:
    runs-on: ubuntu-latest
    needs: [dd-x86_64, dd-aarch64]
    steps:
    - run: curl https://api.day.app/${{ secrets.BARK_KEY }}/NixOS%20Install%20Done/${{ inputs.host }}?icon=https://hydra.nixos.org/logo
