name: "Install OS"
on:
  workflow_dispatch:
    inputs:
      ip:
        description: 'Ip or Domain'
        type: string
        required: true
      flakeAttr:
        description: 'X86-64 OS Config Hostname'
        type: string
        required: true
      user:
        description: 'SSH User'
        required: true
        default: 'root'
        type: choice
        options:
          - root
          - ubuntu

env:
  SSH: ssh -o StrictHostKeyChecking=no
  HOST: root@${{ inputs.ip }}

jobs:

  kexec:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir -m 0755  ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
    - run: |
        until $SSH -o ConnectTimeout=10 ${{ inputs.user }}@${{ inputs.ip }}
        do
          echo "Server Not Reachable, Waiting..."
          sleep 5
        done
    - name: Run Kexec Script
      continue-on-error: true
      run: |
        if [ ${{ inputs.user }} = root ]
        then
          $SSH -o ServerAliveInterval=5 -o ServerAliveCountMax=2 $HOST 'curl -sL http://hydra.mlyxshi.com/job/nixos/flake/kexec-$(uname -m)/latest/download-by-type/file/kexec-script | bash -s'
        else
          $SSH -o ServerAliveInterval=5 -o ServerAliveCountMax=2 ${{ inputs.user }}@${{ inputs.ip }} 'curl -sL http://hydra.mlyxshi.com/job/nixos/flake/kexec-$(uname -m)/latest/download-by-type/file/kexec-script | sudo bash -s'
        fi

  install:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir -m 0755  ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main

    - run: |
        outPath=$(nix build --no-link --print-out-paths .#nixosConfigurations.${{ inputs.flakeAttr }}.config.system.build.toplevel)
        echo "outPath=$outPath" >> "$GITHUB_ENV"

    - run: |
        until $SSH -o ConnectTimeout=10 $HOST ls /sysroot
        do
          echo "Kexec Environment Not Reachable, Waiting..."
          sleep 5
        done
    
    - run: $SSH $HOST parted --script /dev/sda mklabel gpt mkpart "BOOT" fat32  1MiB  512MiB mkpart "NIXOS" ext4 512MiB 100% set 1 esp on
    - run: $SSH $HOST mkfs.fat -F 32 /dev/disk/by-partlabel/BOOT
    - run: $SSH $HOST mkfs.ext4 -F /dev/disk/by-partlabel/NIXOS
    - run: $SSH $HOST mkdir -p /mnt
    - run: $SSH $HOST mount /dev/disk/by-partlabel/NIXOS /mnt
    - run: $SSH $HOST mount --mkdir /dev/disk/by-partlabel/BOOT /mnt/boot

    - run: NIX_SSHOPTS='-o StrictHostKeyChecking=no' nix copy --substitute-on-destination --to ssh://$HOST?remote-store=local?root=/mnt $outPath
 
    - run: $SSH $HOST nix-env --store /mnt -p /mnt/nix/var/nix/profiles/system --set $outPath
    - run: $SSH $HOST mkdir /mnt/{etc,tmp}
    - run: $SSH $HOST touch /mnt/etc/NIXOS
    - run: $SSH $HOST mkdir -p /mnt/persist/sops/ 
    - run: $SSH $HOST curl -sLo /mnt/persist/sops/key ${{ secrets.AGE_KEY_URL }}
    - run: $SSH $HOST NIXOS_INSTALL_BOOTLOADER=1 nixos-enter --root /mnt -- /run/current-system/bin/switch-to-configuration boot
    - run: $SSH $HOST reboot

    - run: curl https://api.day.app/${{ secrets.BARK_KEY }}/NixOS%20Install%20Done/${{ inputs.flakeAttr }}?icon=https://hydra.nixos.org/logo

