name: "Flexget RSS Config"
on:
  push:
    paths: 
      - 'rss.yml'
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest   
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@transmission.mlyxshi.com '[ -e "/persist/flake" ] && rm -rf /persist/flake; update; systemctl restart flexget'