name: "sops-nix Cache"
on:
  push:
  workflow_dispatch:

env:
  NIX_STORE_SIGN_PRIVATE: ${{ secrets.NIX_STORE_SIGN_PRIVATE }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker/setup-qemu-action@master
    - uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 13
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          extra-platforms = aarch64-linux
          substituters = https://cache.nixos.org https://cache.mlyxshi.com
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache:vXjiuWtSTOXj63zr+ZjMvXqvaYIK1atjyyEk+iuIqSg=
    
    - run: echo $NIX_STORE_SIGN_PRIVATE > /tmp/key
    - run: nix copy --to 's3://nix?endpoint=minio.mlyxshi.com&secret-key=/tmp/key&parallel-compression=true&compression=zstd&compression-level=20' .#packages.x86_64-linux.sops-install-secrets