name: "sops-install-secrets Cache"
on:
  push:
  workflow_dispatch:

env:
  ORANC_USERNAME: ${{ github.repository_owner }}
  ORANC_PASSWORD: ${{ github.token }}
  ORANC_SIGNING_KEY: ${{ secrets.NIX_STORE_SIGN_PRIVATE }}

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@master
    - uses: docker/setup-qemu-action@master
    - uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 13
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          extra-platforms = aarch64-linux
          substituters = https://cache.nixos.org https://oranc.li7g.com/ghcr.io/mlyxshi/nix
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache:vXjiuWtSTOXj63zr+ZjMvXqvaYIK1atjyyEk+iuIqSg=
    - run: nix profile install github:linyinfeng/oranc  --extra-substituters https://linyinfeng.cachix.org --extra-trusted-public-keys linyinfeng.cachix.org-1:sPYQXcNrnCf7Vr7T0YmjXz5dMZ7aOKG3EqLja0xr9MM=
    - run: oranc push --registry ghcr.io --repository mlyxshi/nix initialize
    - run: nix build --no-link --print-out-paths .#packages.x86_64-linux.sops-install-secrets | sudo --preserve-env /home/runner/.nix-profile/bin/oranc push --repository mlyxshi/nix
  