name: "System x86_64"
on: [ push, workflow_dispatch ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          substituters = https://cache.nixos.org https://cache.mlyxshi.com
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache:vXjiuWtSTOXj63zr+ZjMvXqvaYIK1atjyyEk+iuIqSg=
    
    - run: git config user.name github-actions[bot] && git config user.email github-actions[bot]@users.noreply.github.com

    - run: |
        nix eval --raw .#nixosConfigurations.sw2.config.system.build.toplevel  > ./path/sw2
    - run: git commit -m "test system"
    - run: git push


