name: "System Upgrade"
on:
  push:
    paths: 
      - 'flake.lock'
  workflow_dispatch:

env:
  SSH: ssh -o StrictHostKeyChecking=no

jobs:
  aarch64:
    runs-on: ubuntu-latest   
    strategy:
      fail-fast: false
      matrix:
        host: [jp1,jp2,us]
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: $SSH root@${{ matrix.host }}.mlyxshi.com '[ -e "/flake" ] && rm -rf /flake; systemctl stop KeepCPUMemory; update; systemctl restart KeepCPUMemory'