name: "System Upgrade"
on:
  push:
    paths: 
      - 'flake.lock'
  workflow_dispatch:

env:
  ORANC_USERNAME: ${{ github.repository_owner }}
  ORANC_PASSWORD: ${{ github.token }}
  ORANC_SIGNING_KEY: ${{ secrets.NIX_STORE_SIGN_PRIVATE }}

jobs:
  cache-sops-nix:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          substituters = https://cache.nixos.org https://oranc.li7g.com/ghcr.io/mlyxshi/nix
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache:vXjiuWtSTOXj63zr+ZjMvXqvaYIK1atjyyEk+iuIqSg=
    - run: nix profile install github:linyinfeng/oranc  --extra-substituters https://linyinfeng.cachix.org --extra-trusted-public-keys linyinfeng.cachix.org-1:sPYQXcNrnCf7Vr7T0YmjXz5dMZ7aOKG3EqLja0xr9MM=
    - run: oranc push --registry ghcr.io --repository mlyxshi/nix initialize
    - run: nix build --no-link --print-out-paths .#packages.x86_64-linux.sops-install-secrets | sudo --preserve-env /home/runner/.nix-profile/bin/oranc push --repository mlyxshi/nix
  
  upgrade-x86-64-Azure:
    runs-on: ubuntu-latest  
    needs:  cache-sops-nix
    strategy:
      fail-fast: false
      matrix:
        host: [kr2, sw2, sw3]  
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ matrix.host }}.mlyxshi.com '[ -e "/persist/flake" ] && rm -rf /persist/flake; update'

  upgrade-x86-64-Oracle:
    runs-on: ubuntu-latest  
    needs:  cache-sops-nix
    strategy:
      fail-fast: false
      matrix:
        host: [hk1, hk2, jp3]
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ matrix.host }}.mlyxshi.com '[ -e "/persist/flake" ] && rm -rf /persist/flake; systemctl stop KeepCPUMemory; update'


  upgrade-aarch64-Oracle:
    runs-on: ubuntu-latest   
    strategy:
      fail-fast: false
      matrix:
        host: [jp2,jp4,sw,de,us1,us2,au,kr]
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ matrix.host }}.mlyxshi.com '[ -e "/persist/flake" ] && rm -rf /persist/flake; systemctl stop KeepCPUMemory; update'