name: "System Upgrade"
on:
  push:
    paths: 
      - 'flake.lock'
  workflow_dispatch:

jobs:
  cache-sops-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker/setup-qemu-action@master
    - uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 13
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          extra-platforms = aarch64-linux
          substituters = https://cache.nixos.org https://cache.mlyxshi.com
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache:vXjiuWtSTOXj63zr+ZjMvXqvaYIK1atjyyEk+iuIqSg=
    
    - run: echo $NIX_STORE_SIGN_PRIVATE > /tmp/key
    - run: nix copy --to 's3://nix?endpoint=minio.mlyxshi.com&secret-key=/tmp/key&parallel-compression=true&compression=zstd&compression-level=20' .#packages.x86_64-linux.sops-install-secrets
  
  upgrade-x86-64:
    runs-on: ubuntu-latest  
    needs:  cache-sops-nix
    strategy:
      fail-fast: false
      matrix:
        host: [kr2, sw2, sw3, hk1, hk2, jp3]
    
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ matrix.host }}.mlyxshi.com '[ -e "/persist/flake" ] && rm -rf /persist/flake; update'

  upgrade-aarch64:
    runs-on: ubuntu-latest   
    strategy:
      fail-fast: false
      matrix:
        host: [jp2,jp4,sw,de,us1,us2,au,kr]
    
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: ssh -o StrictHostKeyChecking=no root@${{ matrix.host }}.mlyxshi.com '[ -e "/persist/flake" ] && rm -rf /persist/flake; update'