name: "System Upgrade"
on:
  push:
    paths: 
      - 'flake.lock'
  workflow_dispatch:

env:
  SSH: ssh -o StrictHostKeyChecking=no

jobs:
  x86-64:
    runs-on: ubuntu-latest  
    strategy:
      fail-fast: false
      matrix:
        host: [sw2, sw3] # kr2: hydra x86-64 
    steps:
    - uses: actions/checkout@master
    - uses: DeterminateSystems/nix-installer-action@main
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: |
        outPath=$(nix build --no-link --print-out-paths .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel)
        echo "outPath=$outPath" >> "$GITHUB_ENV"

    - run: NIX_SSHOPTS='-o StrictHostKeyChecking=no' nix copy --substitute-on-destination --to ssh://${{ matrix.host }} $outPath
    - run: $SSH root@${{ matrix.host }}.mlyxshi.com nix-env --store /mnt -p /mnt/nix/var/nix/profiles/system --set $outPath
    - run: $SSH root@${{ matrix.host }}.mlyxshi.com $outPath/bin/switch-to-configuration switch

  aarch64:
    runs-on: ubuntu-latest   
    strategy:
      fail-fast: false
      matrix:
        host: [jp2,jp4,sw,de,us1,us2,au] # kr: hydra aarch64 
    steps:
    - run: mkdir -m 0755  ~/.ssh && echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 
    - run: $SSH root@${{ matrix.host }}.mlyxshi.com '[ -e "/persist/flake" ] && rm -rf /persist/flake; systemctl stop KeepCPUMemory; update'