name: "Wait fix"
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' #every hour


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@master
    - uses: DeterminateSystems/nix-installer-action@main
    - run: nix build nixpkgs/nixos-unstable#legacyPackages.aarch64-linux.deno && curl https://api.day.app/${{ secrets.BARK_KEY }}/Deno%20Build%20Done/
