name: "Wait fix"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' #every hour


jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@master
    - uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          extra-platforms = aarch64-linux
    - run: |
        path=$(nix eval --raw  github:NixOS/nixpkgs/nixos-unstable#legacyPackages.aarch64-linux.deno)
        # ignore error
        set +e 
        nix path-info  --store https://cache.nixos.org/ -r $path
        [[ $? -eq 0 ]] && curl https://api.day.app/${{ secrets.BARK_KEY }}/Deno%20Build%20Done/
